name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [x86, x86_64, armeabi-v7a, arm64-v8a]

    steps:
      - uses: actions/checkout@v2

      - uses: lukka/run-cmake@v2
        id: runcmake_cmd
        with:
          buildDirectory: ${{ runner.workspace }}/build
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced 
          cmakeAppendedArgs:
            -DCMAKE_TOOLCHAIN_FILE=${ANDROID_SDK_ROOT}/ndk-bundle/build/cmake/android.toolchain.cmake
            -DANDROID_ABI=${{ matrix.abi }}
            -DANDROID_NATIVE_API_LEVEL=16
            -DCMAKE_BUILD_TYPE=Release
